# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2026 Taritolay, Nicolás Daniel <lynceusscan@gmail.com>
"""Product-input framework (no NODE_ID: the AST discovery ignores this module).

A product input imports an existing on-disk product instead of computing it
from the point cloud. Each input is barrier-only: it takes no part in tiling;
its `barrier_task` validates the selected file, copies it to the session's
canonical name (e.g. `chm_mosaic.tif`) and publishes the typed payload, so
downstream consumers treat it exactly as if the product had been generated by
the pipeline.

Two flavors share `barrier_input_file(ctx, target)`:
* table-like inputs (`Input Table`, `Input GeoPackage`) register one row in
  the declarative registry `table/_input_targets.INPUT_TARGETS` keyed by
  NODE_ID;
* rasters (`DTM`/`DSM`/`CHM`/multispectral) are variants of the `Input
  Raster` strategy family, so they target this framework's rows through
  `VARIANT_TARGET` instead (`multispectral` shares the raster branch but
  skips the single-band notice: every band is the product).

Third-party inputs need NO core registration: their `barrier_task` calls
`barrier_input_file` with its OWN target dict
(`node_id`/`node_name`/`output_port`/`session_file`/`kind_label` plus
`kind_group`). The UI side is convention-driven too: any node declaring
`input_file_key` in PROCESSING_SPECS gets the Browse + file-label item
(with `file_filters` from the same specs), and the picked path always
arrives as `ctx["file_path"]`.

This module hosts ONLY the shared machinery (`barrier_input_file` + the
per-kind validation branches), so the `raster/` and `table/` domains never
import each other. `kind_group` selects the validation branch.
"""

from __future__ import annotations

from pathlib import Path


def _raster_validation_warnings(
    path: Path, multiband: bool = False, product: str = "raster"
) -> list[str]:
    """Validation notices for rasters (CRS, georeferencing, bands)."""
    import rasterio
    from rasterio.transform import Affine

    warnings: list[str] = []
    try:
        with rasterio.open(str(path)) as ds:
            if ds.crs is None:
                warnings.append(
                    "Imported raster has no coordinate reference system (CRS); "
                    "downstream nodes may not align with other products."
                )
            if ds.transform == Affine.identity():
                warnings.append(
                    "Imported raster has no geotransform; cells cannot be "
                    "projected to ground coordinates."
                )
            if ds.count > 1 and not multiband:
                warnings.append(
                    f"Imported {product} has {ds.count} bands; "
                    "only band 1 is used."
                )
            if multiband and ds.count < 2:
                warnings.append(
                    f"Expected a multiband {product} with 2+ bands; this file "
                    "has only 1 band — check the selected product."
                )
    except Exception as exc:
        raise RuntimeError(f"Not a valid raster file: {path.name} ({exc})") from exc
    return warnings


def _table_validation_warnings(path: Path) -> list[str]:
    """Validation notices for CSV tables (header + readable rows)."""
    import csv

    warnings: list[str] = []
    try:
        with open(path, newline="", encoding="utf-8-sig") as handle:
            reader = csv.DictReader(handle)
            header = reader.fieldnames or []
            _first = next(reader, None)
    except Exception as exc:
        raise RuntimeError(f"Not a valid CSV file: {path.name} ({exc})") from exc
    if not header:
        warnings.append(
            "Imported CSV has no header row; columns are unknown to the join."
        )
    return warnings


def _gpkg_validation_warnings(path: Path) -> list[str]:
    """Validation notices for GeoPackages (readable SQLite + attribute tables)."""
    import sqlite3

    warnings: list[str] = []
    try:
        con = sqlite3.connect(f"file:{path}?mode=ro", uri=True)
        try:
            tables = [
                row[0]
                for row in con.execute(
                    "SELECT name FROM sqlite_master WHERE type='table' "
                    "AND name NOT LIKE 'gpkg_%' AND name NOT LIKE 'sqlite_%' "
                    "AND name NOT LIKE 'rtree_%' ORDER BY name"
                ).fetchall()
            ]
            if not tables:
                warnings.append(
                    "Imported GeoPackage has no attribute tables to join."
                )
        finally:
            con.close()
    except Exception as exc:
        raise RuntimeError(
            f"Not a valid GeoPackage: {path.name} ({exc})"
        ) from exc
    return warnings


def barrier_input_file(ctx: dict, target: dict) -> dict:
    """Copy/validate a picked external file into the session.

    The file is copied (shutil.copy2) because the session is self-contained:
    its artifacts must not depend on an external file that may disappear
    later. Each input instance writes under `artifacts/<node_iid>/`, so two
    inputs OF THE SAME KIND coexist (F2 path-by-port): downstream nodes
    resolve the copy by port type from `ctx[f"<port_type>_path"]`.
    """
    import shutil

    from lynceus.processing import provenance

    session = Path(ctx["session_dir"])
    src_raw = ctx.get("file_path", "") or ""
    src = Path(src_raw)
    if not src_raw or not src.is_file():
        raise RuntimeError(
            f"{target.get('node_name', 'Input')}: file not found: "
            f"{src_raw or '(none selected)'}"
        )

    warnings: list[str] = []
    kind_group = target.get("kind_group", "raster")
    kind_label = target.get("kind_label", "raster")
    if kind_group in ("none", "custom", ""):
        # Third-party product kinds without a core validation branch:
        # copy faithfully, no format opinions.
        pass
    elif kind_group == "raster":
        warnings.extend(_raster_validation_warnings(src, product=kind_label))
    elif kind_group == "multispectral":
        warnings.extend(
            _raster_validation_warnings(src, multiband=True, product=kind_label)
        )
    elif kind_group == "table_gpkg":
        warnings.extend(_gpkg_validation_warnings(src))
    else:
        warnings.extend(_table_validation_warnings(src))

    dst = session / str(ctx.get("node_iid") or "") / target["session_file"]
    dst.parent.mkdir(parents=True, exist_ok=True)
    # Atomic copy: a crash mid-copy must never leave a half-written
    # product behind (the next run would reuse a corrupt file).
    import os

    tmp = dst.with_name(dst.name + ".tmp")
    shutil.copy2(str(src), str(tmp))
    os.replace(str(tmp), str(dst))

    prov_doc = provenance.build_provenance(ctx, str(dst.name))
    if kind_group in ("raster", "multispectral"):
        provenance.embed_tiff_tags(dst, prov_doc)
    elif kind_group == "table_gpkg":
        provenance.embed_gpkg_metadata(dst, prov_doc)
    provenance.write_sidecar(dst, prov_doc, {"source_file": str(src)})

    payload = {
        "file": str(dst),
        "kind": target.get("kind_label") or target.get("node_name") or "product",
        "node": target.get("node_id", ""),
        "source_file": str(src),
    }
    if warnings:
        payload["warnings"] = warnings
    return payload