# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2026 Taritolay, Nicolás Daniel <lynceusscan@gmail.com>
"""Node - Input Raster (strategy family: imports an existing raster product).

This is a *strategy node*: its ports/capabilities come from a variant selected
in the config (`strategy` key). With no strategy the node is inert (no ports).
The variants are the modules under the same folder whose ``VARIANT_OF`` points
back to this node id; they declare the per-product OUTPUTS/PROCESSING_SPECS
and re-use the shared ``barrier_input_file`` from ``_product_input``.
"""

from __future__ import annotations

from lynceus.nodes._variants import STRATEGY_FIELD

NODE_ID = "lynceus.nodes.raster.input_raster"
NODE_NAME = "Input Raster"
NODE_CATEGORY = "Raster"
NODE_SUBCATEGORY = "Input"

NODE_DESCRIPTION = (
    "<b>Input Raster</b> -- Import an Existing Raster Product<br><br>"
    "Imports an existing raster (DTM, DSM, CHM or multispectral GeoTIFF) "
    "from disk instead of computing it from the point cloud, so a pre-made "
    "product can feed terrain or forestry analysis directly.<br><br>"
    "<b>Process:</b> Choose the product type with the button on the node (or "
    "the Strategy dropdown in the Inspector), then pick the file with Browse. "
    "The selected file is validated (missing CRS or georeferencing raises a "
    "warning) and copied into this run's session as the canonical mosaic, so "
    "downstream nodes consume it exactly as if it had been generated by the "
    "pipeline.<br><br>"
    "<b>Tips:</b> Changing the product type rebuilds the node's ports and cuts "
    "existing connections. Use this to reuse a product you already have "
    "(e.g. a survey-delivered ground model) instead of processing the LiDAR "
    "from scratch."
)

INPUTS = ()
OUTPUTS = ()

PROCESSING_SPECS = {
    "config_schema": {
        STRATEGY_FIELD: {
            "type": "str",
            "default": "",
            "description": (
                "Which raster product this node imports. Selecting one "
                "activates the matching output port "
                "(DTM, DSM, CHM or multispectral)."
            ),
            "impact": (
                "Changing the product rebuilds the node's ports and cuts all "
                "existing connections to it."
            ),
            "group": "Product",
        }
    },
}


def get_config_defaults() -> dict:
    return {STRATEGY_FIELD: ""}