# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2026 Taritolay, Nicolás Daniel <lynceusscan@gmail.com>
"""Node - Input GeoPackage (import an existing GeoPackage table)."""

from __future__ import annotations

from lynceus.nodes._product_input import barrier_input_file
from lynceus.nodes.ports import PortType
from lynceus.nodes.table._input_targets import INPUT_TARGETS

NODE_ID = "lynceus.nodes.table.input_gpkg"
NODE_NAME = "Input GeoPackage"
NODE_CATEGORY = "Table"
NODE_SUBCATEGORY = "Input"

NODE_DESCRIPTION = (
    "<b>Input GeoPackage</b> -- Import an Existing GeoPackage Table<br><br>"
    "Imports an existing GeoPackage table from disk instead of deriving it "
    "from the point cloud, so a table-based pipeline (e.g. joining field "
    "inventories with forest metrics) can start from real data.<br><br>"
    "<b>Process:</b> The selected file is validated (readable SQLite with at "
    "least one attribute table) and copied into this run's session, so "
    "downstream nodes (e.g. Concatenate Tables) consume it exactly as if it "
    "had been generated by the pipeline.<br><br>"
    "<b>Tips:</b> Use this to bring GeoPackage inventories or auxiliary "
    "statistics into a run without pre-processing. Geometry columns are not "
    "exported to CSV by Concatenate Tables. Select the file with the Browse "
    "button on the node."
)

INPUTS = ()
OUTPUTS = (PortType.TABLE_GPKG,)

PROCESSING_SPECS = {
    "barrier_task": "barrier_input_gpkg",
    "output_port": "table_gpkg",
    "output_globs": ("*/rows.gpkg",),
    "input_file_key": "file_path",
    "session_file": "rows.gpkg",
}


def get_config_defaults() -> dict:
    return {}


def barrier_input_gpkg(ctx: dict) -> dict:
    """Import an existing GeoPackage table as the session's table product."""
    return barrier_input_file(ctx, INPUT_TARGETS[NODE_ID])