# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2026 Taritolay, Nicolás Daniel <lynceusscan@gmail.com>
"""Node - Input Table (import an existing CSV table)."""

from __future__ import annotations

from lynceus.nodes._product_input import barrier_input_file
from lynceus.nodes.ports import PortType
from lynceus.nodes.table._input_targets import INPUT_TARGETS

NODE_ID = "lynceus.nodes.table.input_table"
NODE_NAME = "Input Table"
NODE_CATEGORY = "Table"
NODE_SUBCATEGORY = "Input"

NODE_DESCRIPTION = (
    "<b>Input Table</b> -- Import an Existing Table<br><br>"
    "Imports an existing CSV table from disk instead of deriving it from the "
    "point cloud, so a table-based pipeline (e.g. joining ascii inventories "
    "with forest metrics) can start from real data.<br><br>"
    "<b>Process:</b> The selected file is validated (readable header + rows) "
    "and copied into this run's session, so downstream nodes (e.g. Concatenate "
    "Tables) consume it exactly as if it had been generated by the pipeline.<br><br>"
    "<b>Tips:</b> Use this to bring plot inventories, field tables or "
    "auxiliary statistics into a run without pre-processing. "
    "Select the file with the Browse button on the node."
)

INPUTS = ()
OUTPUTS = (PortType.TABLE_CSV,)

PROCESSING_SPECS = {
    "barrier_task": "barrier_input_table",
    "output_port": "table_csv",
    "output_globs": ("*/table.csv",),
    "input_file_key": "file_path",
    "session_file": "table.csv",
}


def get_config_defaults() -> dict:
    return {}


def barrier_input_table(ctx: dict) -> dict:
    """Import an existing CSV table as the session's table product."""
    return barrier_input_file(ctx, INPUT_TARGETS[NODE_ID])